### ISSUE TITLE
Confirmatie e-mail

### ISSUE THREAD

**Issue by MaartenDeBosschere** [CenEkaGent/site#5]
Er zijn al een aantal mensen die mij gevraagd hebben om de confirmatie e-mail terug te brengen. Dus wanneer je je voor een activiteit inschrijft dat je daar een e-mail van krijgt.

**Comment by OriginalUsername314** [comment]
@rgdvilde Ik zou hier toch ook wel voor willen pleiten. Als er in deze mail dan nog een iCalendar bestand zit, staan de activiteiten meteen in de mensen hun agenda, wat ook wel nuttig is.
